name: 'linux env opcut-builder'
# version: '3.8'

services:
  build-linux:
    build:
      context: .
      dockerfile: src/docker/linux.dockerfile
    volumes:
      - ./output:/mnt
    command: cp /libopcut.so /mnt/
